name: DotnetProject
on: push
jobs:
 dotnetdeployment:
   runs-on: self-hosted
   steps:
     - name: checkout
       uses: actions/checkout@v6.0.2
       with:
        ref: master
     - name: workingdir
       run:  pwd
     - name: docker compose
       run: docker compose up -d -f docker-compose.yml
      


