name: DotnetProject
on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter database username"
        required: true
        default: appuser
        type: string
   
jobs:
 dotnetdeployment:
   runs-on: self-hosted
   environment: dev
   env:
    DB_NAME: ${{vars.DB}}
    DB_USER: ${{ github.event.inputs.username }}
#    DB_USER: ${{vars.USER}}
    DB_PASSWORD: ${{secrets.DB_PASSWORD}}
   
   steps:
     - name: checkout
       uses: actions/checkout@v6.0.2
       with:
        ref: master
     - name: workingdir
       run:  pwd
     - name: docker compose down
       run: docker compose -f docker-compose.yml down
     - name: docker remove volume Remove
       continue-on-error: true
       run: docker volume remove devopspractice_pgdata
     - name: Remove images
       run: docker rmi $(docker images -q)
     - name: docker compose down
       run: docker compose -f docker-compose.yml up -d  






